### ISSUE TITLE
Daemon always on

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/hyperdrive-daemon-app#2]
**User story**
As a content creator
I want my profile and content to continuously synchronize to the network
so that my work is more available and more quickly updated

**Acceptance criteria**
- [x] The Daemon can stay alive for extended periods of time
- [x] The Daemon has an option to launch upon OS startup

**Comment by juliangruber** [comment]
> * The Daemon can installed with the option to launch upon OS startup

Our installers don't allow for any options, for now as long as we don't have an opening screen I think this can be managed via the tray menu.

**Comment by jameslibscie** [comment]
> > * The Daemon can installed with the option to launch upon OS startup
> 
> Our installers don't allow for any options, for now as long as we don't have an opening screen I think this can be managed via the tray menu.

Good one. I have removed the specific method of implementation from the specs, via the tray or (later) a settings screen is fine. I think it should be on by default btw. Do you agree?

**Comment by juliangruber** [comment]
I disagree, I find apps that decide to auto launch very annoying personally. Except for the ones I trust, like Dropbox. What about sending a notification on first launch, asking the user to enable auto start if they want?

**Comment by jameslibscie** [comment]
Sounds good!

**Comment by juliangruber** [comment]
> * CPU, memory usage and network traffic of the Daemon is measured and reported

I don't know of any app that exposes CPU and memory usage itself. Don't people use the task manager, Activity.app etc for such?

**Comment by juliangruber** [comment]
About network traffic: This isn't something the Daemon is exposing yet, and it's risky for us to show in the tray menu as we need to reopen the menu whenever we want to change content it displays. What about we create a new issue for network stats and figure out the way there?

Does Windows have network stats? In mac I can see how much network an app uses:

<img width="912" alt="Screenshot 2020-04-20 at 11 17 42" src="https://user-images.githubusercontent.com/10247/79735432-931ef000-82f8-11ea-86e9-3c6af265c33a.png">

**Comment by jameslibscie** [comment]
My intention with this was for us to (be able to) do some kind of performance measurement. This could involve simply watching the task manager while it runs on several different machines or using some other external tool, perhaps also (later?) with larger files or larger numbers of modules. What do you think would be appropriate at this point?

**Comment by juliangruber** [comment]
Ok that's helpful context :) What about using our machine's native tools for this?

Otherwise we're getting into the field of submitting usage statistics, which requires infrastructure and data policies.

**Comment by jameslibscie** [comment]
Oh yeah, it's definitely enough for now to just use the stats from our own machines and monitor that way. I think if we take a look every now and then while testing, that should be sufficient. Keep our eyes open for crazy spikes or anything unusual. Perhaps we can later add some kind of performance logging (off by default) for test and troubleshooting purposes.

**Comment by jameslibscie** [comment]
I've reworded the spec to a "sanity check" on the performance metrics.

**Comment by juliangruber** [comment]
Great! Can we split this out to a separate issue? It doesn't have anything to do with "always on" per so

**Comment by jameslibscie** [comment]
Performance check split off into #26
